Import("env")
lockSimulation = env.Program(target = 'lock_simulation', source = ['lock_simulation_driver.cc','lock_simulator.cc', 'lock_manager.cc', 'lock_client.cc'], LIBS=['rdmacm', 'ibverbs', 'pthread' ,'rt'])
binaries = [lockSimulation]
Return("binaries")
